#!/bin/sh

#
# Copyright (C) 2015 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Authored by: Michi Henning <michi.henning@canonical.com>
#

set -e  # Fail if any command fails.
set -x

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR

PATH=$PATH:/usr/bin
eval export `dpkg-architecture -s`
export
LIB_DIR=/usr/lib/$DEB_HOST_MULTIARCH
export LD_LIBRARY_PATH=$LIB_DIR:$LD_LIBRARY_PATH

echo "PATH: $PATH"
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
echo "MULTI: $DEB_HOST_MULTIARCH"
echo "LIB_DIR: $LIB_DIR"
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"

cp /usr/share/doc/persistent-cache-cpp/examples/string_cache.cpp .
cp /usr/share/doc/persistent-cache-cpp/examples/person_cache.cpp .

g++ --std=c++11 -o string_cache string_cache.cpp -L${LIB_DIR} `pkg-config --cflags --libs libpersistent-cache-cpp`
[ -x string_cache ]
g++ --std=c++11 -o person_cache person_cache.cpp -L${LIB_DIR} `pkg-config --cflags --libs libpersistent-cache-cpp`
[ -x person_cache ]

./string_cache
./person_cache
